DROP DATABASE IF EXISTS Sip;
CREATE DATABASE Sip;

USE Sip;

CREATE TABLE profiles (
    Id INT NULL AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    drink VARCHAR(255) NOT NULL
);